# Kompozycja Docker
# docker/docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: printer-emulator/api
    container_name: printer-emu-api
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
      - ../output:/app/output
      - ../models:/app/models
      - ../reports:/app/reports
      - ../logs:/app/logs
      - ../config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    command: ["api"]
    networks:
      - printer-emu-network
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: printer-emulator/web
    container_name: printer-emu-web
    ports:
      - "8080:8080"
    volumes:
      - ../data:/app/data
      - ../output:/app/output
      - ../models:/app/models
      - ../reports:/app/reports
      - ../logs:/app/logs
      - ../config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - API_URL=http://api:5000
    command: ["web"]
    networks:
      - printer-emu-network
    depends_on:
      - api
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: printer-emu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - printer-emu-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: printer-emu-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - printer-emu-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: printer-emu-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../config/grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - printer-emu-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  printer-emu-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data: